import os
import storage_utils

class Project(object):
    """
    We have to store our documents for using them in various projects.
    The projects has the following attributes:
        - project name which identify the project
        - description of the project goals
        - members
        - documents
    """
    def __init__(self, name, description, members=None, documents=None):
        if members is None:
            members = []
        if documents is None:
            documents = []
        self.name = name
        self.description = description
        self.members = members
        self.documents = documents

    def has_required_roles(self):
        """
        We have to guarantee that there is at least one manager and one administrator in the project.
        :return: True or False
        """
        manager = False
        admin = False
        for member in self.members:
            if member.role == "manager":
                manager = True
            if member.role == "admin":
                admin = True
        return manager and admin


class ProjectManager(object):
    """
    Creating, listing and removing projects
    """

    def __init__(self, project_location, user_manager):
        self.project_location = project_location
        self.user_manager = user_manager

    def save_project(self, project_id, project):
        """
        Writes the project into a file under repository/project
        :param project_id: unique ID generated by storage_utils
        :param project: Project type object
        """
        with open(os.path.join(self.project_location, str(project_id)), 'w') as project_file:
            project_file.write(project.name + '\n')
            project_file.write(project.description + '\n')
            project_file.write(str(project.members) + '\n')
            project_file.write(str(project.documents) + '\n')

    def add_project(self, project):
        """
        Creates the project's ID and calls save_project
        :param project: a Project type Object
        :return: ID of the project
        """
        project_id = storage_utils.get_next_id(self.project_location)
        self.save_project(project_id, project)
        return project_id

    def update_project(self, project_id, project):
        """
        Remove and then re-creates the project
        :param project_id: unique ID generated by storage_utils
        :param project: a Project type Object
        """
        self.remove_project(project_id)
        self.save_project(project_id, project)

    def remove_project(self, project_id):
        """
        Deletes the project from the repository/project folder
        :param document_id: unique ID generated by storage_utils
        """
        project_file_path = os.path.join(self.project_location, str(project_id))
        if os.path.exists(project_file_path):
            os.remove(project_file_path)
        else:
            raise ValueError('The project {} does not exist!'.format(project_id))

    def list_project(self):
        """
        Lists the project in the repository
        :return: list of projects
        """
        return [p for p in os.listdir(self.project_location)
                if os.path.isfile(os.path.join(self.project_location, p))]

    def load_project(self, project_id):
        """
        Reads the project from the repository
        :param document_id: unique ID generated by storage_utils
        :return: project type object
        """
        with open(os.path.join(self.project_location, str(project_id))) as project_file:
            name = project_file.readline().strip()
            description = project_file.readline().strip()
            members = project_file.readline().strip()
            documents = project_file.readline().strip()
        return Project(name, description, members, documents)

    def find_project_by_id(self, project_id):
        """
        Search for project in the repository based on ID
        :param document_id: unique ID generated by storage_utils
        :return: project type object, or raise ValueError
        """
        project_file_path = os.path.join(self.project_location, str(project_id))
        if os.path.exists(project_file_path):
            return self.load_project(project_id)
        else:
            raise ValueError('The project {} does not exist!'.format(project_id))

    def count_projects(self):
        """
        Calculates the number of projects in the repository
        :return: # of projects
        """
        return len(os.listdir(self.project_location))
